import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  manifest: "/manifest.json",
  metadataBase: new URL('http://localhost:3000'),
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title:'공유시 제목',
    description:'공유 요약 정보',
    image:'/logo512.png'    
  },
  twitter: {
    title: 'Title webtsite',
    description: 'this is the desciption',
    image:'/logo512.png'
  },
  icons:{
    icon:'/icons/favicon-16x16.png',
    apple:'/icons/favicon-16x16.png',
    shortcut:'/logo512.png',
    other:{
      rel:'apple-touch-icon-precomposed',
      url: '/icons/apple-touch-icon-57x57.png',
    }
  },
  keywords:['next','react','routing'],
  authors:[{name:'minkyu'}],
  robots:{
    index:false,
    follow:true,
    nocache:true,
    googlebot:{
      index:true,
      follow:false,
    }
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
